server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-7xv2012nfi836h8908o.mysql.rds.aliyuncs.com:3306/heima?useSSL=false&serverTimezone=UTC
    username: lvjiayu
    password: Lvjiayu20126493
  redis:
    host: 43.139.41.3
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: lvjiayu20126493
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug